name: Parallel Courts Scraper

on:
  schedule:
    - cron: "15 2 * * 4"
  push:
    paths:
      - .github/workflows/courts-scrape.yml

jobs:
  parallel-scraper:
    name: Parallel Courts Scraper
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
          persist-credentials: false
          fetch-depth: 0
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: "2.0.1"
      - name: Scrape
        run: |
          poetry install
          poetry run gv-dashboard-data scrape-courts-portal --ntasks 40 --debug
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git pull origin master
          git add -f gun_violence_dashboard_data/data/processed/scraped_courts_data*
          git commit -m "Add courts scraper data"
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          branch: master
          github_token: ${{ secrets.GITHUB_TOKEN }}
